### ISSUE TITLE
`my_yolo.process` doesn't return `ObjectList` at present.

### ISSUE THREAD

**Issue by vulcan25** [vulcan25/image_processor#1]
In the following code, at `processor/my_yolo.py`, `ObjectList` is deliberately not returned:
``` 
def process(input_stream):     
     start_time = time.time()
     is_success, output_stream = yolo.detect_img(input_stream)
     io_buf = io.BytesIO(output_stream)
#    return is_success, io_buf.read(), ObjectList
     print("--- %s seconds ---" % (time.time() - start_time))
     return is_success, io_buf.read()   
```
This is because although `type(ObjectList)` returns `list` I thnk some of the list elements are of `cv2` datatypes.   This isn't ideal, as the flask frontend would show `Module Not Found: cv2` when trying to parse this list.  I want to avoid including this dep in the flask container..

A workaround could be found for this; either parse `ObjectList` here and take out any `cv2` datatypes, then return a plain list, and possibly write that output to a central datastore (redis maybe).

**Comment by simonfreeman80** [comment]
A possible work around:
In image_detect.py/detect_image, before the return you can include
`det_no = len(out_boxes)`
`return image, ObjectsList, det_no`

Than in the app.py
`return jsonify({'id': url_for('view', filename=filename)},{'detections': dect_no},{'objects': print(objs)})`

Objectslist will be simple a string casting, but the detection integer number helps understand at API level is processed image got some positive match

**Comment by vulcan25** [comment]
Thanks for your input!, here's my take...

Have a look at this commit on the `pass-objects-back` branch: https://github.com/vulcan25/image_processor/commit/431f989721613f7a51e2b1082721e61fe63a036f

I'd noticed that `image_detect.py` had this in the `detect_image` method:
```
             label = '{} {:.2f}'.format(predicted_class, score) 
             # label = '{}'.format(predicted_class) 
```
I'm not sure why whoever wrote this picked the first line here.  I switched this round, which means for an item in the ObjectsList, `item[6]` is literally a string like 'person'.

With the other mods in that commit, if you submit a curl request, the response is something like:
```
{"id":"/view/a1cd83a2-ad54-4e71-be2c-073e2486da1a",
 "info":{"objects":["sports ball","handbag","person","person","person","person"],
 "success":true}}
```
This seemed sensible, as you could then count occurences of 'person` in the list to get a total count of people found in that image.

Also in the `process` function, instead of returning the `is_success` boolean, I've changed this to return a dict:
```
    info = {'success': is_success,
            'objects': [d[6] for d in ObjectsList],
            }

    return info, io_buf.read()
```
I think this is better, as it means you could add further values to the return in future, without necessarily modifying the frontend code.

Interested in your take on this :D  This is all pretty new to me.

**Comment by vulcan25** [comment]
I've merged this in, see https://github.com/vulcan25/image_processor/commit/e5dccf3291b7f1f8da78366951c13abc22b37a32

This includes display on the frontend, but not for mode (2) where jobs are submitted via rq.

![catdog](https://user-images.githubusercontent.com/6283434/71938918-da013380-31a8-11ea-8ba8-c195cda8e786.png)

**Comment by simonfreeman80** [comment]
Hi, just wondering if will be possible to add the accuracy rate gathered by the model in processing output into JSON reply: I'll be definetely usefull for use the API.
Looking to "image_detect.py" seems score is in '7' position in the Objectlist:

`ObjectsList.append([top, left, bottom, right, mid_v, mid_h, label, scores])`

So probably needs to be added in "my_yolo.py" here?


```
def process(input_stream):
     start_time = time.time()
     is_success, output_stream, ObjectsList  = yolo.detect_img(input_stream)
     io_buf = io.BytesIO(output_stream)
     print("--- %s seconds ---" % (time.time() - start_time))
     **objects = [d[6] for d in ObjectsList]**
     info = {'success': is_success,
             'objects': objects,
             'object_string': ' '.join(get_object_string(objects)),
             }
     return info, io_buf.read()
```

Thx!!!

**Comment by vulcan25** [comment]
DONE.  In this commit: https://github.com/vulcan25/image_processor/commit/1c3f9c59aea706d519994061ecb832eb8bea8159

Now the output from the `curl` is:
```
{'id': '/view/0e595889-1aa5-44b3-a8ee-27efedaed82e',
 'info': {'object_string': 'handbag:1,  sports ball:1,  person:4, ',
          'objects': ['sports ball',
                      'handbag',
                      'person',
                      'person',
                      'person',
                      'person'],
          'scored_objects': [{'object': 'sports ball', 'score': '0.57'},
                             {'object': 'handbag', 'score': '0.30'},
                             {'object': 'person', 'score': '0.99'},
                             {'object': 'person', 'score': '0.99'},
                             {'object': 'person', 'score': '1.00'},
                             {'object': 'person', 'score': '1.00'}],
          'success': True}}
```
I haven't added any frontend code for this, as you can see.

---

However (the following is an FYI, and for my own understanding).  Lets take a better look at this.  I add some quick diag code to the `process` function, as soon as `ObjectsList` is available:

```
     print (ObjectsList)
     for a in ObjectsList:
         for i, b in enumerate(a):
             print (i, b, type(b))
             print ('----------')
     exit()
```
So now I can manually run this from the interpreter (within the processor container):
```
docker exec -it image_processor_processor_1 /bin/bash

# wget http://example.com/hydrant.jpg

# python

>>> from my_yolo import process
>>> with open('hydrant.jpg','rb') as f:
...  process(f.read())
... 
--- 3.374058246612549 seconds ---
[[45, 385, 420, 556, 470.5, 232.5, 'fire hydrant', '1.00']]
0 45 <class 'numpy.int32'>
1 385 <class 'numpy.int32'>
2 420 <class 'numpy.int32'>
3 556 <class 'numpy.int32'>
4 470.5 <class 'numpy.float64'>
5 232.5 <class 'numpy.float64'>
6 fire hydrant <class 'str'>
7 1.00 <class 'str'>
----------
```

Seems, according to [this](https://stackoverflow.com/questions/9452775/converting-numpy-dtypes-to-native-python-types) to get those numpy types back into python types you can just use `numpytype.item()`:

```
>>> import numpy as np

>>> x = np.int32(2)
>>> type(x.item())
<class 'int'>

>>> y = np.float64(3.14)
>>> type(y.item())
<class 'float'>
```

So it would be maybe sensible to edit the `image_detect.py` code to output these instead, or you could mod `my_yolo.py` with some code to output all of this, including the bounding boxes.

For another day.
