### ISSUE TITLE
Adding Boundary Box into JSON response

### ISSUE THREAD

**Issue by simonfreeman80** [vulcan25/image_processor#5]
Hi @vulcan25 , 
after last commit is possible to have this output in API call:
`{'id': '/view/0e595889-1aa5-44b3-a8ee-27efedaed82e',
 'info': {'object_string': 'handbag:1,  sports ball:1,  person:4, ',
          'objects': ['sports ball'],
          'scored_objects': [{'object': 'sports ball', 'score': '0.57'}],
          'success': True}}`

I'm interested also to add the detection boundary BOX cord into JSON reply(xmin,ymin, xmax.ymax), something like:
`{'id': '/view/0e595889-1aa5-44b3-a8ee-27efedaed82e',
 'info': {'object_string': 'handbag:1,  sports ball:1,  person:4, ',
          'objects': ['sports ball'],
          'scored_objects': [{'object': 'sports ball', 'score': '0.57', 'xmin':'43', 'ymin':'123', 'xmax':'332','ymax':'12020'}],
          'success': True}}`

In **image_detect.py** all matched cords are specified into "detect_image" method, line 127:
`top, left, bottom, right = box`
and are appended into ObjectList (line 149)
`ObjectsList.append([top, left, bottom, right, mid_v, mid_h, label, scores])`

It's not clear to me how to add those into info JSON structure from "my_yolo.py".

Can you pls gimme some tips? many thanks!

**Comment by vulcan25** [comment]
Calling these values `xmin, ymin, xmax, ymax` rather than `top, left, bottom, right` seems like adding a layer of obfuscation to this.

Would you be happy with the latter, `top, left, bottom, right` alongside `mid_v` and `mid_h` being in the JSON response.

It seems like we should keep the terminology from image_detect.py, would that work for you since I think you're the only user haha.

**Comment by simonfreeman80** [comment]
Hi @vulcan25, think you are right, let's preserve the original terminology.
I'm also thinking on how use it on a live video stream, maybe using FFMPEG to grab screenshot to process.
Thx.

**Comment by vulcan25** [comment]
Right that worked :D this mod feels a bit dirty, cause we're essentially just restructuring the `ObjectsList` in the `score_objects` function, which makes me wonder if I should have just modified `image_detect.py` to return a friendlier `ObjectsList`.  I think when I started this, initially I wanted to keep the tutorial code unmodified, hence tending towards this method.

Either way, you now have everything in the `ObjectsList` in the JSON response.
